version: '1.0.{build}'
configuration:
  - Debug
  - Release
platform: Any CPU
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
  - ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
  - appveyor-retry dotnet restore -v Minimal
build_script:
  - dotnet build "src\websocket-sharp" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
after_build:
  - dotnet pack "src\websocket-sharp" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
artifacts:
  - path: artifacts\**\*.*
cache:
  - '%USERPROFILE%\.nuget\packages'
deploy:
  provider: NuGet
  api_key:
    secure: 9ScXmZWbIAXrGlhIlDcncmK6e9TEzBtfGNoNDCjHH371csaZUD3AGFoNexLHXeMW
  skip_symbols: true
  artifact: /.*\.nupkg/
  
